"""fix hero_slide columns to match frontend contract

Revision ID: ff796ed357d7
Revises: d97d3de87a7c
Create Date: 2026-09-09 13:17:27.316994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff796ed357d7'
down_revision: Union[str, None] = 'd97d3de87a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero_slides', sa.Column('image', sa.String(), nullable=False))
    op.add_column('hero_slides', sa.Column('video_url', sa.String(), nullable=True))
    op.add_column('hero_slides', sa.Column('eyebrow', sa.String(), nullable=True))
    op.add_column('hero_slides', sa.Column('cta_label', sa.String(), nullable=True))
    op.add_column('hero_slides', sa.Column('cta_href', sa.String(), nullable=True))
    op.drop_column('hero_slides', 'cta_text')
    op.drop_column('hero_slides', 'image_url')
    op.drop_column('hero_slides', 'cta_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero_slides', sa.Column('cta_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hero_slides', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('hero_slides', sa.Column('cta_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('hero_slides', 'cta_href')
    op.drop_column('hero_slides', 'cta_label')
    op.drop_column('hero_slides', 'eyebrow')
    op.drop_column('hero_slides', 'video_url')
    op.drop_column('hero_slides', 'image')
    # ### end Alembic commands ###
